version: 2
jobs:

  build:
    working_directory: ~/pixu
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-yarn-{{ checksum "yarn.lock" }}
            - pixu-yarn-
      - run:
          name: Update yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              yarn global add greenkeeper-lockfile@1 --prefix ~/.yarn
              ~/.yarn/bin/greenkeeper-lockfile-update
            fi
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Upload yarn.lock [greenkeeper]
          command: |
            if [[ "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              ~/.yarn/bin/greenkeeper-lockfile-upload
            fi
      - run:
          name: Check that yarn.lock matches package.json
          command: |
            if [[ ! "${CIRCLE_BRANCH}" =~ greenkeeper\/.* ]]; then
              [[ $(git diff --name-only yarn.lock) == "" ]] && exit 0
              echo ">> yarn.lock is out of date, run \"yarn\""
              exit 1
            fi
      - save_cache:
          key: pixu-yarn-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache/yarn"
      - save_cache:
          key: pixu-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - "~/pixu/node_modules"

  build-node-6:
    working_directory: ~/pixu
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-node6-{{ checksum "yarn.lock" }}
            - pixu-node6-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: pixu-node6-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache/yarn"
      - save_cache:
          key: pixu-node6-modules-{{ checksum "yarn.lock" }}
          paths:
            - "~/pixu/node_modules"

  lint:
    working_directory: ~/pixu
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-node-modules-{{ checksum "yarn.lock" }}
            - pixu-node-modules-
      - run:
          name: Set $PATH
          command: echo 'export PATH=~/pixu/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Lint JS
          command: gulp eslint
      - run:
          name: Lint Sass
          command: gulp sasslint

  test-sass:
    working_directory: ~/pixu
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-node-modules-{{ checksum "yarn.lock" }}
            - pixu-node-modules-
      - run:
          name: Set $PATH
          command: echo 'export PATH=~/pixu/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Test Sass
          command: gulp sasstest

  test-js:
    working_directory: ~/pixu
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-node-modules-{{ checksum "yarn.lock" }}
            - pixu-node-modules-
      - run:
          name: Set $PATH
          command: echo 'export PATH=~/pixu/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run JS Tests
          command: gulp jstest
      - run:
          name: Run Client JS Tests
          command: gulp clienttest
      - run:
          name: Report Test Coverage
          command: |
            nyc report --reporter=text-lcov | coveralls
            nyc report --reporter=text-lcov --temp-directory ./jscov/client/ | coveralls
            curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_number]=${CIRCLE_BUILD_NUM}&payload[status]=done"
          environment:
            COVERALLS_PARALLEL: 'true'
      - run:
          name: Check Test Coverage
          command: |
            nyc check-coverage
            nyc check-coverage --temp-directory ./jscov/client/
      - store_artifacts:
          path: jscov
          destination: js-reports
      - store_test_results:
          path: jscov

  test-node-6:
    working_directory: ~/pixu
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - pixu-node6-modules-{{ checksum "yarn.lock" }}
            - pixu-node6-modules-
      - run:
          name: Set $PATH
          command: echo 'export PATH=~/pixu/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run JS Tests [node 6]
          command: gulp jstest
      - run:
          name: Check Test Coverage [node 6]
          command: nyc check-coverage
      - store_artifacts:
          path: jscov
          destination: js-reports
      - store_test_results:
          path: jscov

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - build-node-6
      - lint:
          requires:
            - build
      - test-sass:
          requires:
            - build
      - test-js:
          requires:
            - build
      - test-node-6:
          requires:
            - build-node-6
